name: build-all
on: [push]
jobs:
  build-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web
      #- run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/ # or path/to/artifact
      - uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/ # or path/to/artifact

